README.md
index.js
package.json
utils/fetchGitDiff.js
utils/resolveMainTask.js

- Added support to configure base branch in consuming app's package.json
- git diff command changed

[Feature] Configure Base Branch

---

index.js
package.json
utils/common.js
utils/fetchGitDiff.js
yarn.lock

Fix: Exit process on failure while executing `git diff` command

[BUGFIX] Exit process on failure while executing git diff command

---

yarn.lock

Removed unused packages from yarn.lock file

[INTERNAL] Updated yarn.lock

---

index.js
package.json
yarn.lock

Removed please-upgrade-node package

[INTERNAL] Removed unwanted packages

---

index.js
package.json
utils/common.js
utils/fetchGitDiff.js
yarn.lock

Skip the linters for the base branch

[PATCH] Skip the linters for the base branch

---

index.js
package.json
utils/common.js
utils/fetchGitDiff.js
yarn.lock

Cache successful linted commit hash

[FEATURE] Cache successful linted commit hash

---

package.json
yarn.lock

Update eslint to fix loadash security issue
Issue link: https://snyk.io/test/npm/lodash/4.17.4

[INTERNAL] Update eslint to fix loadash security issue

---

index.js

[INTERNAL] Log more info for debugging

---

README.md

[BUGFIX] Fix typo in Readme.md

---

README.md

[PATCH] Added Monthly Downloads batch

---

README.md

[PATCH] Updated readme badge links

---

README.md

Added npmtrends link to downloads badge

[PATCH] Added npmtrends link to downloads badge

---

README.md

Show total downloads count instead of monthly downloads

[PATCH] Show total downloads count instead of monthly downloads

---

README.md

[PATCH] Downloads badge text change

---

.eslintrc.js
.travis.yml
README.md
package.json
tests/index.js
yarn.lock

- Added a few basic tests using mocha and chai

[INTERNAL] Added basic tests using mocha and chai

---

index.js
utils/common.js

- Use searchSync() to fetch user configuration using cosmiconfig

[PATCH] use searchSync() to fetch user configuration using cosmiconfig

---

package.json
yarn.lock

- `eslint` version bump to `v6.0.1`
- `eslint-plugin-node` version bump to `v9.1.0`

[INTERNAL] eslint version bump to v6.x

---

.github/stale.yml

Added stale GitHub bot to automatically close inactive pull requests

[INTERNAL] Added stale.yml to automatically close inactive pull requests

---

index.js
utils/fetchGitDiff.js

Base PR: https://github.com/theenadayalank/lint-prepush/pull/30

feat: use currentBranch for diff if it has already been pushed to remote

---

README.md
utils/resolveMainTask.js

Add concurrency "toggle"

---

README.md

- Incorrect node version in README.md file

docs: Incorrect node version in readme

---

README.md

remove travis ci badge in readme.me

remove travis ci badge in readme.me

---

package.json

Bump version to v2.2.2

---

.github/workflows/npm-publish.yml
package.json

downmerge from master to develop

downmerge from master to develop

---

README.md
src/constants.js
src/lint-prepush.js
src/utils/checkForBranchExistence.js
src/utils/fetchGitDiff.js
src/utils/getAllTrackedFiles.js

- Updated base branch to main from master

Updated base branch to main from master
